### ISSUE TITLE
Switch to using the Slackmojis API

### ISSUE THREAD

**Issue by jkupferman** [tacyarg/slackmojis#2]
Greetings!
Slackmojis creator here. I came across your project and was super excited to see someone had made a downloader package and published it for everyone to use. Thanks for making this.

I noticed you were downloading the homepage and extracting the emojis via CSS selector. There is in fact an API that would make your code a lot more stable, it is available here: https://slackmojis.com/emojis.json

It is also worth noting that as of April of this year the home page only shows up to 50 emojis per category, thus scraping this home page wont yield all the emojis. So many more great ones left to be discovered!

Happy to help in any way I can.

**Comment by tacyarg** [comment]
Hello, thank you for reaching out @jkupferman 
I will create a new release soon supporting the API.

**Comment by tacyarg** [comment]
Done.
https://github.com/tacyarg/slackmojis/releases/tag/1.1.0
