### ISSUE TITLE
Add support for Slackmojis API pagination

### ISSUE THREAD

**Issue by jkupferman** [tacyarg/slackmojis#5]
Hi folks, Slackmojis creator here. 

As of yesterday the Slackmojis API endpoint is now paginated. It turns out returning 40k objects in one good might not have been a great idea 😬. 

https://slackmojis.com/emojis.json?page=0 now returns the first 500 emojis. Keep incrementing the page number until you get back and empty array response, meaning you've hit the end. There are currently ~40 pages.

Sorry about springing this on you, I should have given folks more of a heads up.

Cheers.

**Comment by tacyarg** [comment]
Thank you for reporting this, I will be committing a fix shortly!
